export const adresTurleri = [
  { value: "elektronik", label: "Elektronik Tebligat Adresi" },
  { value: "yurt-ici-isyeri", label: "Yurt İçi İşyeri Adresi" },
  { value: "yurtdisi-isyeri", label: "Yurtdışı İşyeri Adresi" },
  { value: "yurt-ici-ikametgah", label: "Yurt içi İkametgah Adresi" },
  { value: "askerlik", label: "Askerlik Adresi" },
  { value: "yurtdisi-ikametgah", label: "Yurtdışı İkametgah Adresi" },
  { value: "cezaevi", label: "Cezaevi Adresi" },
]

export const iller = [
  { value: "01", label: "Adana" },
  { value: "02", label: "Adıyaman" },
  { value: "03", label: "Afyonkarahisar" },
  { value: "04", label: "Ağrı" },
  { value: "05", label: "Amasya" },
  { value: "06", label: "Ankara" },
  { value: "07", label: "Antalya" },
  { value: "08", label: "Artvin" },
  { value: "09", label: "Aydın" },
  { value: "10", label: "Balıkesir" },
  { value: "11", label: "Bilecik" },
  { value: "12", label: "Bingöl" },
  { value: "13", label: "Bitlis" },
  { value: "14", label: "Bolu" },
  { value: "15", label: "Burdur" },
  { value: "16", label: "Bursa" },
  { value: "17", label: "Çanakkale" },
  { value: "18", label: "Çankırı" },
  { value: "19", label: "Çorum" },
  { value: "20", label: "Denizli" },
  { value: "21", label: "Diyarbakır" },
  { value: "22", label: "Edirne" },
  { value: "23", label: "Elazığ" },
  { value: "24", label: "Erzincan" },
  { value: "25", label: "Erzurum" },
  { value: "26", label: "Eskişehir" },
  { value: "27", label: "Gaziantep" },
  { value: "28", label: "Giresun" },
  { value: "29", label: "Gümüşhane" },
  { value: "30", label: "Hakkâri" },
  { value: "31", label: "Hatay" },
  { value: "32", label: "Isparta" },
  { value: "33", label: "Mersin" },
  { value: "34", label: "İstanbul" },
  { value: "35", label: "İzmir" },
  { value: "36", label: "Kars" },
  { value: "37", label: "Kastamonu" },
  { value: "38", label: "Kayseri" },
  { value: "39", label: "Kırklareli" },
  { value: "40", label: "Kırşehir" },
  { value: "41", label: "Kocaeli" },
  { value: "42", label: "Konya" },
  { value: "43", label: "Kütahya" },
  { value: "44", label: "Malatya" },
  { value: "45", label: "Manisa" },
  { value: "46", label: "Kahramanmaraş" },
  { value: "47", label: "Mardin" },
  { value: "48", label: "Muğla" },
  { value: "49", label: "Muş" },
  { value: "50", label: "Nevşehir" },
  { value: "51", label: "Niğde" },
  { value: "52", label: "Ordu" },
  { value: "53", label: "Rize" },
  { value: "54", label: "Sakarya" },
  { value: "55", label: "Samsun" },
  { value: "56", label: "Siirt" },
  { value: "57", label: "Sinop" },
  { value: "58", label: "Sivas" },
  { value: "59", label: "Tekirdağ" },
  { value: "60", label: "Tokat" },
  { value: "61", label: "Trabzon" },
  { value: "62", label: "Tunceli" },
  { value: "63", label: "Şanlıurfa" },
  { value: "64", label: "Uşak" },
  { value: "65", label: "Van" },
  { value: "66", label: "Yozgat" },
  { value: "67", label: "Zonguldak" },
  { value: "68", label: "Aksaray" },
  { value: "69", label: "Bayburt" },
  { value: "70", label: "Karaman" },
  { value: "71", label: "Kırıkkale" },
  { value: "72", label: "Batman" },
  { value: "73", label: "Şırnak" },
  { value: "74", label: "Bartın" },
  { value: "75", label: "Ardahan" },
  { value: "76", label: "Iğdır" },
  { value: "77", label: "Yalova" },
  { value: "78", label: "Karabük" },
  { value: "79", label: "Kilis" },
  { value: "80", label: "Osmaniye" },
  { value: "81", label: "Düzce" },
]

export const ilceler: Record<string, Array<{ value: string; label: string }>> = {
  "34": [
    // İstanbul
    { value: "adalar", label: "Adalar" },
    { value: "arnavutkoy", label: "Arnavutköy" },
    { value: "atasehir", label: "Ataşehir" },
    { value: "avcilar", label: "Avcılar" },
    { value: "bagcilar", label: "Bağcılar" },
    { value: "bahcelievler", label: "Bahçelievler" },
    { value: "bakirkoy", label: "Bakırköy" },
    { value: "basaksehir", label: "Başakşehir" },
    { value: "bayrampasa", label: "Bayrampaşa" },
    { value: "besiktas", label: "Beşiktaş" },
    { value: "beykoz", label: "Beykoz" },
    { value: "beylikduzu", label: "Beylikdüzü" },
    { value: "beyoglu", label: "Beyoğlu" },
    { value: "buyukcekmece", label: "Büyükçekmece" },
    { value: "catalca", label: "Çatalca" },
    { value: "cekmece", label: "Çekmeköy" },
    { value: "esenler", label: "Esenler" },
    { value: "esenyurt", label: "Esenyurt" },
    { value: "eyupsultan", label: "Eyüpsultan" },
    { value: "fatih", label: "Fatih" },
    { value: "gaziosmanpasa", label: "Gaziosmanpaşa" },
    { value: "gungoren", label: "Güngören" },
    { value: "kadikoy", label: "Kadıköy" },
    { value: "kagithane", label: "Kâğıthane" },
    { value: "kartal", label: "Kartal" },
    { value: "kucukcekmece", label: "Küçükçekmece" },
    { value: "maltepe", label: "Maltepe" },
    { value: "pendik", label: "Pendik" },
    { value: "sancaktepe", label: "Sancaktepe" },
    { value: "sariyer", label: "Sarıyer" },
    { value: "silivri", label: "Silivri" },
    { value: "sisli", label: "Şişli" },
    { value: "sultanbeyli", label: "Sultanbeyli" },
    { value: "sultangazi", label: "Sultangazi" },
    { value: "tuzla", label: "Tuzla" },
    { value: "umraniye", label: "Ümraniye" },
    { value: "uskudar", label: "Üsküdar" },
    { value: "zeytinburnu", label: "Zeytinburnu" },
  ],
  "06": [
    // Ankara
    { value: "akyurt", label: "Akyurt" },
    { value: "altindag", label: "Altındağ" },
    { value: "ayash", label: "Ayaş" },
    { value: "bala", label: "Bala" },
    { value: "beypazari", label: "Beypazarı" },
    { value: "camlidere", label: "Çamlıdere" },
    { value: "cankaya", label: "Çankaya" },
    { value: "cubuk", label: "Çubuk" },
    { value: "elmdag", label: "Elmadağ" },
    { value: "etimesgut", label: "Etimesgut" },
    { value: "evren", label: "Evren" },
    { value: "golbasi", label: "Gölbaşı" },
    { value: "gudul", label: "Güdül" },
    { value: "haymana", label: "Haymana" },
    { value: "kahramankazan", label: "Kahramankazan" },
    { value: "kalecik", label: "Kalecik" },
    { value: "kecioren", label: "Keçiören" },
    { value: "kizilcahamam", label: "Kızılcahamam" },
    { value: "mamak", label: "Mamak" },
    { value: "nallihan", label: "Nallıhan" },
    { value: "polatli", label: "Polatlı" },
    { value: "pursaklar", label: "Pursaklar" },
    { value: "sincan", label: "Sincan" },
    { value: "sereflikochisar", label: "Şereflikoçhisar" },
    { value: "yenimahalle", label: "Yenimahalle" },
  ],
  "35": [
    // İzmir
    { value: "aliaga", label: "Aliağa" },
    { value: "balcova", label: "Balçova" },
    { value: "bayindir", label: "Bayındır" },
    { value: "bayrakli", label: "Bayraklı" },
    { value: "bergama", label: "Bergama" },
    { value: "bornova", label: "Bornova" },
    { value: "buca", label: "Buca" },
    { value: "cesme", label: "Çeşme" },
    { value: "cigli", label: "Çiğli" },
    { value: "dikili", label: "Dikili" },
    { value: "foca", label: "Foça" },
    { value: "gaziemir", label: "Gaziemir" },
    { value: "guzelbahce", label: "Güzelbahçe" },
    { value: "karabaglar", label: "Karabağlar" },
    { value: "karaburun", label: "Karaburun" },
    { value: "karsiyaka", label: "Karşıyaka" },
    { value: "kemalpasa", label: "Kemalpaşa" },
    { value: "kinik", label: "Kınık" },
    { value: "kiraz", label: "Kiraz" },
    { value: "konak", label: "Konak" },
    { value: "menderes", label: "Menderes" },
    { value: "menemen", label: "Menemen" },
    { value: "narlidere", label: "Narlıdere" },
    { value: "odemis", label: "Ödemiş" },
    { value: "seferihisar", label: "Seferihisar" },
    { value: "selcuk", label: "Selçuk" },
    { value: "tire", label: "Tire" },
    { value: "torbali", label: "Torbalı" },
    { value: "urla", label: "Urla" },
  ],
  // Add more provinces and their districts as needed
}

export const getIlcelerByIl = (ilCode: string) => {
  return ilceler[ilCode] || []
}
