export interface AdliyeData {
  [province: string]: string[]
}

export const adliyeListesi: AdliyeData = {
  İSTANBUL: [
    "Adalar Adliye",
    "Bakırköy Adliye",
    "Beykoz Adliye",
    "Büyükçekmece Adliye",
    "Çatalca Adliye",
    "Gaziosmanpaşa Adliye",
    "İstanbul Adliye",
    "İstanbul Anadolu Adliye",
    "Küçükçekmece Adliye",
    "Silivri Adliye",
    "Şile Adliye",
  ],
  ANKARA: [
    "Akyurt Adliye",
    "Ankara Adliye",
    "Ankara Batı Adliye",
    "Bala Adliye",
    "Beypazarı Adliye",
    "Çubuk Adliye",
    "Elmadağ Adliye",
    "Gölbaşı(Ankara) Adliye",
    "Haymana Adliye",
    "Kahramankazan Adliye",
    "Kalecik Adliye",
    "Kızılcahamam Adliye",
    "Nallıhan Adliye",
    "Polatlı Adliye",
    "Şereflikoçhisar Adliye",
  ],
  İZMİR: [
    "Aliağa Adliye",
    "Bayındır Adliye",
    "Bergama Adliye",
    "Çeşme Adliye",
    "Dikili Adliye",
    "Foça Adliye",
    "İzmir Adliye",
    "Karaburun Adliye",
    "Karşıyaka Adliye",
    "Kemalpaşa Adliye",
    "Kınık Adliye",
    "Kiraz Adliye",
    "Menderes Adliye",
    "Menemen Adliye",
    "Ödemiş Adliye",
    "Seferihisar Adliye",
    "Selçuk Adliye",
    "Tire Adliye",
    "Torbalı Adliye",
    "Urla Adliye",
  ],
  ADANA: [
    "Adana Adliye",
    "Aladağ Adliye",
    "Ceyhan Adliye",
    "Feke Adliye",
    "İmamoğlu Adliye",
    "Karaisalı Adliye",
    "Karataş Adliye",
    "Kozan Adliye",
    "Pozantı Adliye",
    "Tufanbeyli Adliye",
    "Yumurtalık Adliye",
  ],
  ADIYAMAN: ["Adıyaman Adliye", "Besni Adliye", "Gerger Adliye", "Gölbaşı(Adıyaman) Adliye", "Kahta Adliye"],
  AFYONKARAHİSAR: [
    "Afyonkarahisar Adliye",
    "Bolvadin Adliye",
    "Çay Adliye",
    "Dazkırı Adliye",
    "Dinar Adliye",
    "Emirdağ Adliye",
    "İscehisar Adliye",
    "Sandıklı Adliye",
    "Sinanpaşa Adliye",
    "Şuhut Adliye",
  ],
  AĞRI: [
    "Ağrı Adliye",
    "Diyadin Adliye",
    "Doğubayazıt Adliye",
    "Eleşkirt Adliye",
    "Patnos Adliye",
    "Taşlıçay Adliye",
    "Tutak Adliye",
  ],
  AMASYA: ["Amasya Adliye", "Gümüşhacıköy Adliye", "Merzifon Adliye", "Suluova Adliye", "Taşova Adliye"],
  ANTALYA: [
    "Akseki Adliye",
    "Alanya Adliye",
    "Antalya Adliye",
    "Demre Adliye",
    "Elmalı Adliye",
    "Finike Adliye",
    "Gazipaşa Adliye",
    "Gündoğmuş Adliye",
    "Kaş Adliye",
    "Kemer Adliye",
    "Korkuteli Adliye",
    "Kumluca Adliye",
    "Manavgat Adliye",
    "Serik Adliye",
  ],
  ARTVİN: ["Arhavi Adliye", "Artvin Adliye", "Borçka Adliye", "Hopa Adliye", "Şavşat Adliye", "Yusufeli Adliye"],
  AYDIN: [
    "Aydın Adliye",
    "Bozdoğan Adliye",
    "Çine Adliye",
    "Didim(Yenihisar) Adliye",
    "Germencik Adliye",
    "Karacasu Adliye",
    "Kuşadası Adliye",
    "Nazilli Adliye",
    "Söke Adliye",
  ],
  BALIKESİR: [
    "Ayvalık Adliye",
    "Balıkesir Adliye",
    "Bandırma Adliye",
    "Bigadiç Adliye",
    "Burhaniye Adliye",
    "Dursunbey Adliye",
    "Edremit Adliye",
    "Erdek Adliye",
    "Gönen(Balıkesir) Adliye",
    "İvrindi Adliye",
    "Kepsut Adliye",
    "Manyas Adliye",
    "Marmara Adliye",
    "Savaştepe Adliye",
    "Sındırgı Adliye",
    "Susurluk Adliye",
  ],
  BİLECİK: ["Bilecik Adliye", "Bozüyük Adliye", "Gölpazarı Adliye", "Osmaneli Adliye", "Söğüt Adliye"],
  BİNGÖL: ["Bingöl Adliye", "Genç Adliye", "Karlıova Adliye", "Kiğı Adliye", "Solhan Adliye"],
  BİTLİS: [
    "Adilcevaz Adliye",
    "Ahlat Adliye",
    "Bitlis Adliye",
    "Güroymak Adliye",
    "Hizan Adliye",
    "Mutki Adliye",
    "Tatvan Adliye",
  ],
  BOLU: ["Bolu Adliye", "Gerede Adliye", "Göynük Adliye", "Mengen Adliye", "Mudurnu Adliye"],
  BURDUR: ["Bucak Adliye", "Burdur Adliye", "Gölhisar Adliye", "Tefenni Adliye", "Yeşilova Adliye"],
  BURSA: [
    "Bursa Adliye",
    "Gemlik Adliye",
    "İnegöl Adliye",
    "İznik Adliye",
    "Karacabey Adliye",
    "Keles Adliye",
    "Mudanya Adliye",
    "Mustafakemalpaşa Adliye",
    "Orhaneli Adliye",
    "Orhangazi Adliye",
    "Yenişehir Adliye",
  ],
  ÇANAKKALE: [
    "Ayvacık Adliye",
    "Bayramiç Adliye",
    "Biga Adliye",
    "Çan Adliye",
    "Çanakkale Adliye",
    "Ezine Adliye",
    "Gelibolu Adliye",
    "Gökçeada Adliye",
    "Lapseki Adliye",
    "Yenice(Çanakkale) Adliye",
  ],
  ÇANKIRI: ["Çankırı Adliye", "Çerkeş Adliye", "Ilgaz Adliye", "Kurşunlu Adliye", "Şabanözü Adliye"],
  ÇORUM: [
    "Alaca Adliye",
    "Bayat(Çorum) Adliye",
    "Ç Test Adliye",
    "Çorum Adliye",
    "İskilip Adliye",
    "Kargı Adliye",
    "Osmancık Adliye",
    "Sungurlu Adliye",
    "Test Mülhakat Tek Hakimli Adliye",
  ],
  DENİZLİ: [
    "Acıpayam Adliye",
    "Buldan Adliye",
    "Çal Adliye",
    "Çameli Adliye",
    "Çardak Adliye",
    "Çivril Adliye",
    "Denizli Adliye",
    "Kale(Denizli) Adliye",
    "Sarayköy Adliye",
    "Tavas Adliye",
  ],
  DİYARBAKIR: [
    "Bismil Adliye",
    "Çermik Adliye",
    "Çınar Adliye",
    "Çüngüş Adliye",
    "Dicle Adliye",
    "Diyarbakır Adliye",
    "Eğil Adliye",
    "Ergani Adliye",
    "Hani Adliye",
    "Hazro Adliye",
    "Kulp Adliye",
    "Lice Adliye",
    "Silvan Adliye",
  ],
  EDİRNE: ["Edirne Adliye", "Enez Adliye", "İpsala Adliye", "Keşan Adliye", "Uzunköprü Adliye"],
  ELAZIĞ: ["Elazığ Adliye", "Karakoçan Adliye", "Keban Adliye", "Kovancılar Adliye", "Maden Adliye", "Palu Adliye"],
  ERZİNCAN: [
    "Çayırlı Adliye",
    "Erzincan Adliye",
    "İliç Adliye",
    "Kemah Adliye",
    "Kemaliye Adliye",
    "Refahiye Adliye",
    "Tercan Adliye",
  ],
  ERZURUM: [
    "Aşkale Adliye",
    "Çat Adliye",
    "Erzurum Adliye",
    "Hınıs Adliye",
    "Horasan Adliye",
    "İspir Adliye",
    "Karayazı Adliye",
    "Oltu Adliye",
    "Pasinler Adliye",
    "Şenkaya Adliye",
    "Tekman Adliye",
    "Tortum Adliye",
  ],
  ESKİŞEHİR: ["Beylikova Adliye", "Çifteler Adliye", "Eskişehir Adliye", "Mihalıççık Adliye", "Sivrihisar Adliye"],
  GAZİANTEP: ["Araban Adliye", "Gaziantep Adliye", "İslahiye Adliye", "Nizip Adliye", "Nurdağı Adliye"],
  GİRESUN: [
    "Alucra Adliye",
    "Bulancak Adliye",
    "Dereli Adliye",
    "Espiye Adliye",
    "Giresun Adliye",
    "Görele Adliye",
    "Şebinkarahisar Adliye",
    "Tirebolu Adliye",
  ],
  GÜMÜŞHANE: ["Gümüşhane Adliye", "Kelkit Adliye", "Şiran Adliye", "Torul Adliye"],
  HAKKARİ: ["Çukurca Adliye", "Hakkari Adliye", "Şemdinli Adliye", "Yüksekova Adliye"],
  HATAY: [
    "Altınözü Adliye",
    "Dörtyol Adliye",
    "Erzin Adliye",
    "Hassa Adliye",
    "Hatay Adliye",
    "İskenderun Adliye",
    "Kırıkhan Adliye",
    "Reyhanlı Adliye",
    "Samandağ Adliye",
    "Yayladağı Adliye",
  ],
  ISPARTA: [
    "Eğirdir Adliye",
    "Isparta Adliye",
    "Keçiborlu Adliye",
    "Senirkent Adliye",
    "Sütçüler Adliye",
    "Şarkikaraağaç Adliye",
    "Yalvaç Adliye",
  ],
  MERSİN: [
    "Anamur Adliye",
    "Aydıncık(Mersin) Adliye",
    "Erdemli Adliye",
    "Gülnar Adliye",
    "Mersin Adliye",
    "Mut Adliye",
    "Silifke Adliye",
    "Tarsus Adliye",
  ],
  KARS: ["Arpaçay Adliye", "Digor Adliye", "Kağızman Adliye", "Kars Adliye", "Sarıkamış Adliye", "Selim Adliye"],
  KASTAMONU: [
    "Araç Adliye",
    "Azdavay Adliye",
    "Cide Adliye",
    "Devrekani Adliye",
    "İnebolu Adliye",
    "Kastamonu Adliye",
    "Küre Adliye",
    "Taşköprü Adliye",
    "Tosya Adliye",
  ],
  KAYSERİ: [
    "Bünyan Adliye",
    "Develi Adliye",
    "İncesu Adliye",
    "Kayseri Adliye",
    "Pınarbaşı(Kayseri) Adliye",
    "Sarıoğlan Adliye",
    "Sarız Adliye",
    "Tomarza Adliye",
    "Yahyalı Adliye",
    "Yeşilhisar Adliye",
  ],
  KIRKLARELİ: [
    "Babaeski Adliye",
    "Demirköy Adliye",
    "Kırklareli Adliye",
    "Lüleburgaz Adliye",
    "Pınarhisar Adliye",
    "Vize Adliye",
  ],
  KIRŞEHİR: ["Kaman Adliye", "Kırşehir Adliye", "Mucur Adliye"],
  KOCAELİ: ["Gebze Adliye", "Gölcük Adliye", "Kandıra Adliye", "Karamürsel Adliye", "Kocaeli Adliye", "Körfez Adliye"],
  KONYA: [
    "Akşehir Adliye",
    "Beyşehir Adliye",
    "Bozkır Adliye",
    "Cihanbeyli Adliye",
    "Çumra Adliye",
    "Doğanhisar Adliye",
    "Ereğli(Konya) Adliye",
    "Hadim Adliye",
    "Ilgın Adliye",
    "Kadınhanı Adliye",
    "Karapınar Adliye",
    "Konya Adliye",
    "Kulu Adliye",
    "Sarayönü Adliye",
    "Seydişehir Adliye",
    "Yunak Adliye",
  ],
  KÜTAHYA: ["Altıntaş Adliye", "Emet Adliye", "Gediz Adliye", "Kütahya Adliye", "Simav Adliye", "Tavşanlı Adliye"],
  MALATYA: [
    "Akçadağ Adliye",
    "Arapgir Adliye",
    "Darende Adliye",
    "Doğanşehir Adliye",
    "Hekimhan Adliye",
    "Malatya Adliye",
    "Pütürge Adliye",
  ],
  MANİSA: [
    "Akhisar Adliye",
    "Alaşehir Adliye",
    "Demirci Adliye",
    "Gördes Adliye",
    "Kırkağaç Adliye",
    "Kula Adliye",
    "Manisa Adliye",
    "Salihli Adliye",
    "Sarıgöl Adliye",
    "Saruhanlı Adliye",
    "Selendi Adliye",
    "Soma Adliye",
    "Turgutlu Adliye",
  ],
  KAHRAMANMARAŞ: [
    "Afşin Adliye",
    "Andırın Adliye",
    "Elbistan Adliye",
    "Göksun Adliye",
    "Kahramanmaraş Adliye",
    "Pazarcık Adliye",
    "Türkoğlu Adliye",
  ],
  MARDİN: [
    "Dargeçit Adliye",
    "Derik Adliye",
    "Kızıltepe Adliye",
    "Mardin Adliye",
    "Mazıdağı Adliye",
    "Midyat Adliye",
    "Nusaybin Adliye",
    "Ömerli Adliye",
    "Savur Adliye",
  ],
  MUĞLA: [
    "Bodrum Adliye",
    "Datça Adliye",
    "Fethiye Adliye",
    "Köyceğiz Adliye",
    "Marmaris Adliye",
    "Milas Adliye",
    "Muğla Adliye",
    "Ortaca Adliye",
    "Seydikemer Adliye",
    "Yatağan Adliye",
  ],
  MUŞ: ["Bulanık Adliye", "Malazgirt Adliye", "Muş Adliye", "Varto Adliye"],
  NEVŞEHİR: [
    "Avanos Adliye",
    "Derinkuyu Adliye",
    "Gülşehir Adliye",
    "Hacıbektaş Adliye",
    "Kozaklı Adliye",
    "Nevşehir Adliye",
    "Ürgüp Adliye",
  ],
  NİĞDE: ["Bor Adliye", "Çamardı Adliye", "Çiftlik Adliye", "Niğde Adliye", "Ulukışla Adliye"],
  ORDU: [
    "Akkuş Adliye",
    "Aybastı Adliye",
    "Fatsa Adliye",
    "Gölköy Adliye",
    "Gürgentepe Adliye",
    "Korgan Adliye",
    "Kumru Adliye",
    "Mesudiye Adliye",
    "Ordu Adliye",
    "Perşembe Adliye",
    "Ünye Adliye",
  ],
  RİZE: ["Çayeli Adliye", "Kalkandere Adliye", "Pazar(Rize) Adliye", "Rize Adliye"],
  SAKARYA: [
    "Akyazı Adliye",
    "Ferizli Adliye",
    "Geyve Adliye",
    "Hendek Adliye",
    "Karasu Adliye",
    "Kaynarca Adliye",
    "Kocaali Adliye",
    "Pamukova Adliye",
    "Sakarya Adliye",
    "Sapanca Adliye",
  ],
  SAMSUN: [
    "Alaçam Adliye",
    "Bafra Adliye",
    "Çarşamba Adliye",
    "Havza Adliye",
    "Kavak Adliye",
    "Ladik Adliye",
    "Samsun Adliye",
    "Terme Adliye",
    "Vezirköprü Adliye",
  ],
  SİİRT: ["Baykan Adliye", "Eruh Adliye", "Kurtalan Adliye", "Pervari Adliye", "Siirt Adliye", "Şirvan Adliye"],
  SİNOP: [
    "Ayancık Adliye",
    "Boyabat Adliye",
    "Durağan Adliye",
    "Gerze(Sinop) Adliye",
    "Sinop Adliye",
    "Türkeli Adliye",
  ],
  SİVAS: [
    "Divriği Adliye",
    "Gemerek Adliye",
    "Gürün Adliye",
    "İmranlı Adliye",
    "Kangal Adliye",
    "Koyulhisar Adliye",
    "Sivas Adliye",
    "Suşehri Adliye",
    "Şarkışla Adliye",
    "Yıldızeli Adliye",
    "Zara Adliye",
  ],
  TEKİRDAĞ: [
    "Çerkezköy Adliye",
    "Çorlu Adliye",
    "Hayrabolu Adliye",
    "Malkara Adliye",
    "Marmaraereğlisi Adliye",
    "Muratlı Adliye",
    "Saray(Tekirdağ) Adliye",
    "Şarköy Adliye",
    "Tekirdağ Adliye",
  ],
  TOKAT: [
    "Almus Adliye",
    "Artova Adliye",
    "Erbaa Adliye",
    "Niksar Adliye",
    "Reşadiye Adliye",
    "Tokat Adliye",
    "Turhal Adliye",
    "Zile Adliye",
  ],
  TRABZON: [
    "Akçaabat Adliye",
    "Araklı Adliye",
    "Çaykara Adliye",
    "Maçka Adliye",
    "Of Adliye",
    "Sürmene Adliye",
    "Tonya Adliye",
    "Trabzon Adliye",
    "Vakfıkebir Adliye",
  ],
  TUNCELİ: [
    "Çemişgezek Adliye",
    "Hozat Adliye",
    "Mazgirt Adliye",
    "Nazımiye Adliye",
    "Ovacık(Tunceli) Adliye",
    "Pertek Adliye",
    "Pülümür Adliye",
    "Tunceli Adliye",
  ],
  ŞANLIURFA: [
    "Akçakale Adliye",
    "Birecik Adliye",
    "Bozova Adliye",
    "Ceylanpınar Adliye",
    "Halfeti Adliye",
    "Harran Adliye",
    "Hilvan Adliye",
    "Siverek Adliye",
    "Suruç Adliye",
    "Şanlıurfa Adliye",
    "Viranşehir Adliye",
  ],
  UŞAK: ["Banaz Adliye", "Eşme Adliye", "Sivaslı Adliye", "Uşak Adliye"],
  VAN: [
    "Bahçesaray Adliye",
    "Başkale Adliye",
    "Çaldıran Adliye",
    "Çatak Adliye",
    "Erciş Adliye",
    "Gevaş Adliye",
    "Gürpınar Adliye",
    "Muradiye Adliye",
    "Özalp Adliye",
    "Saray(Van) Adliye",
    "Van Adliye",
  ],
  YOZGAT: [
    "Akdağmadeni Adliye",
    "Boğazlıyan Adliye",
    "Çayıralan Adliye",
    "Çekerek Adliye",
    "Sarıkaya Adliye",
    "Sorgun Adliye",
    "Şefaatli Adliye",
    "Yerköy Adliye",
    "Yozgat Adliye",
  ],
  ZONGULDAK: [
    "Alaplı Adliye",
    "Çaycuma Adliye",
    "Devrek Adliye",
    "Gökçebey Adliye",
    "KDZ.Ereğli Adliye",
    "Zonguldak Adliye",
  ],
  AKSARAY: ["Aksaray Adliye", "Eskil Adliye", "Ortaköy(Aksaray) Adliye"],
  BAYBURT: ["Bayburt Adliye"],
  KARAMAN: ["Ermenek Adliye", "Karaman Adliye", "Sarıveliler Adliye"],
  KIRIKKALE: ["Delice Adliye", "Keskin Adliye", "Kırıkkale Adliye", "Sulakyurt Adliye"],
  BATMAN: ["Batman Adliye", "Gercüş Adliye", "Kozluk Adliye", "Sason Adliye"],
  ŞIRNAK: ["Beytüşşebap Adliye", "Cizre Adliye", "İdil Adliye", "Silopi Adliye", "Şırnak Adliye", "Uludere Adliye"],
  BARTIN: ["Amasra Adliye", "Bartın Adliye", "Ulus Adliye"],
  ARDAHAN: ["Ardahan Adliye", "Göle Adliye", "Hanak Adliye", "Posof Adliye"],
  IĞDIR: ["Aralık Adliye", "Iğdır Adliye", "Tuzluca Adliye"],
  YALOVA: ["Yalova Adliye"],
  KARABÜK: ["Eskipazar Adliye", "Karabük Adliye", "Safranbolu Adliye", "Yenice(Karabük) Adliye"],
  KİLİS: ["Kilis Adliye"],
  OSMANİYE: ["Bahçe Adliye", "Düziçi Adliye", "Kadirli Adliye", "Osmaniye Adliye"],
  DÜZCE: ["Akçakoca Adliye", "Düzce Adliye", "Yığılca Adliye"],
}

// Helper function to get all provinces
export const getProvinces = (): string[] => {
  return Object.keys(adliyeListesi)
}

// Helper function to get courthouses for a specific province
export const getCourthouses = (province: string): string[] => {
  return adliyeListesi[province] || []
}

// Helper function to get all courthouses as a flat array
export const getAllCourthouses = (): string[] => {
  return Object.values(adliyeListesi).flat()
}
